# Generated by Django 3.1.7 on 2021-06-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210614_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile1',
        ),
    ]
