# Generated by Django 3.1.7 on 2021-06-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210615_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile1',
            new_name='Profile',
        ),
    ]
